name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub 
        run: docker login -u anfasmuhammed  -p 8590183325@Anfas 

      - name: Build Docker Image
        run: docker build -t anfasmuhammed/work-way .

      - name: Publish Image to Docker Hub
        run: docker push anfasmuhammed/work-way:latest

  deploy:
    needs: build   
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull anfasmuhammed/work-way:latest
      - name: Delete old container
        run: docker rm -f work-way-container
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name work-way-container \
          -e MONGO_URL="mongodb+srv://anfasmuhammed936:anfasmuhammed8590@cluster0.6hcxbof.mongodb.net/" \
          -e APP_KEY="bblb rymg relu gtax" \
          -e GOOGLE_CLIENT_ID="595057220047-km2nier9h3400o0qlana9n8ael9ngsk8.apps.googleusercontent.com" \
          -e GOOGLE_CLIENT_SECRET="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" \
          -e GITHUB_CLIENT_ID="Ov23ctqzed3uPPb06cRU" \
          -e GITHUB_CLIENT_SECRET="4658dd9aaac31282cf10d8e2aef6523eb79d78ca" \
          -e JWT_KEY="djhfasddfvfefv" \
          -e JWT_REFRESHKEY="jdfhjdfjfd" \
          -e BACKEND_URL="http://localhost:5000" \
          -e FRONTEND_URL="http://localhost:3000" \
          -e PORT="5000" \
          -e S3_ACCESS_KEY="AKIAXXWC5Z5CNLX5GD4P" \
          -e S3_SECRET_KEY="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" \
          -e REGION="ap-southeast-2" \
          anfasmuhammed/work-way:latest