name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u anfasmuhammed -p 8590183325@Anfas --password-stdin.

      - name: Build Docker Image
        run: docker build -t anfasmuhammed/work-way .

      - name: Publish Image to Docker Hub
        run: docker push anfasmuhammed/work-way:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull anfasmuhammed/work-way:latest

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name work-way-container -e MONGO_URL='${{secrets.MONGO_URL}}  anfasmuhammed/work-way'
