name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u anfasmuhammed  -p 8590183325@Anfas

      - name: Build Docker Image
        run: docker build -t anfasmuhammed/work-way .

      - name: Publish Image to Docker Hub
        run: docker push anfasmuhammed/work-way:latest 

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull anfasmuhammed/work-way:latest
      - name: Delete old container
        run:  docker rm -f work-way-container 
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name work-way-container  anfasmuhammed/work-way:latest'
