name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t anfasmuhammed/work-way .

      - name: Publish Image to Docker Hub
        run: docker push anfasmuhammed/work-way:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull anfasmuhammed/work-way:latest

      - name: Run Docker Container
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: docker run -d -p 5000:5000 --name work-way-container -e MONGO_URL=$MONGO_URL anfasmuhammed/work-way:latest
